/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SQS.Lambda;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testQueueMessage() {
        Library classUnderTest = new Library();
        // 100% thanks to Nick Paro for help on this

    }
}
